# Generated by Django 6.0.3 on 2026-06-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='updated_at',
        ),
    ]
